-- Q1. What is the revenue generated by male vs female customer ?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the avg purchase amount ?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating ?
select item_purchased, Round(Avg(review_rating::numeric),2) as "Avg Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Q5. Do subscribed customer spent more? Compare average spending spend and total revenue 
-- between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
SUM(purchase_amount) as total_spend
from customer
group by subscription_status
order by total_spend desc, avg_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
		ROUND(
				100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric/COUNT(*), 
				2
		) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
WITH customer_type as (
select customer_id,
		previous_purchases,
		CASE 
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END 
		AS customer_segment
from customer
)

select customer_segment,
		COUNT(*) AS "Number of Customers"
FROM customer_type
Group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category
with item_counts as (
	select item_purchased, category,
	COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
